# IDS
TELEGRAM_BOT_TOKEN = "6633590096:AAHo7LoX34cCNVb69XgZ0TVVJZps1VwAmIM"
STICKER_ID = "CAACAgIAAxkBAAEELi9iMn0OEmHYmgzRioq85IgOFDC6ewACowwAAp_SuUvME4_1uMMLmyME"


# DATABASE
DATABASE_PATH = "sqlite:///db/db_users.db"


# USER FLAGS
FREE = "FREE"
WORKING = "WORKING"
